name: gcptflint test
on: [push]

env:
  message: "conversation"
jobs:
  gcptflint:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out our code
        uses: actions/checkout@master
      - name: login to artifact
        run: |
          docker login artifactory.build.ingka.ikea.com:443 -u DPS-CCOE --password "$SECRET"
        env:
          SECRET: ${{ secrets.TOKEN }}
      - name: Pull gcptflint docker image
        run: |
          docker pull artifactory.build.ingka.ikea.com:443/ingka-docker-shared-local/gcptflint:v0.1.0_gcp
      - name: Run gcptflint
        run: |
          docker run -v ${PWD}:/data artifactory.build.ingka.ikea.com:443/ingka-docker-shared-local/gcptflint:v0.1.0_gcp
  # my_job:
  #   needs: my_build
  #   container:
  #     image: eu.gcr.io/ingka-ice-unittest-dev/gcptflint:v0.1.0_gcp
  #     volumes:
  #       - my_docker_volume:/volume_mount
